[package]
name = "autosynth"
version = "0.2.0"
edition = "2024"

[features]
default = ["live"]
live = ["dep:subsecond", "dep:dioxus-devtools"]

[dependencies]
anyhow = "1.0"
cpal = "0.15"
rand = "0.10.0"
subsecond = { version = "0.7", optional = true }
dioxus-devtools = { version = "0.7", optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
