pub mod automation;
pub mod duration;
pub mod effect_config;
pub mod effects;
pub mod engine;
pub mod event;
pub mod filter;
pub mod harmony;
#[cfg(feature = "live")]
pub mod live;
pub mod notes;
pub mod oscillator;
pub mod patch;
pub mod pattern;
pub mod prelude;
pub mod sample;
pub mod sampler;
#[cfg(feature = "live")]
pub(crate) mod midi;
#[cfg(feature = "live")]
pub mod scene;
pub mod score;
pub mod session;
pub mod synth;
pub mod track;
pub mod waveform;

pub(crate) mod envelope;

#[cfg(feature = "live")]
pub use live::live;
